### PR TITLE
pl_PL.json

### PR DESCRIPTION
**Pull request by kostek00**
Some minor tweaks.

### CODE REVIEW

**Comment by ParticleCore** [comment]
I'm going to accept this time because I know it might be kind of hard to understand the instructions, but the commit title should be the name of the native language (`Polski`) and not (`pl_PL.json`), which is what is described in the instructions:

> - Once the locale has been properly created or updated, the commit title (usually where it reads `Create xx_XX.json` or `Update xx_XX.json`) must be completely replaced with the language name in its native form. Using the previous example for a Russian locale, the commit title must have only the original name `Русский` and nothing else.

In the future I'll have to reject it until the instructions are followed.

**Comment by kostek00** [comment]
I actually understand that it meant right after you accepted and wanted to cancel it. Sorry about that I still don't understand how exactly github works. Now I know what and where it will show this name.

**Comment by kostek00** [comment]
By the way you actually copied wrong name instead "Polski" you copied "Русский" to Polish language.

**Comment by ParticleCore** [comment]
Thanks for the heads up, completely messed that one up!

**Comment by Royalgamer06** [comment]
Why is his acceptable, while mine was not?

**Comment by ParticleCore** [comment]
@Royalgamer06 It wasn't: https://github.com/ParticleCore/Iridium/pull/308 and I explained in my reply after the second time.

**Pull request merged**
