### PR TITLE
Polski

### PR DESCRIPTION
**Pull request by Gilukm**
Here's an initial polish translation.

### CODE REVIEW

**Comment by aszwajkowski** [comment]
In my opinion previous [pull request](https://github.com/ParticleCore/Iridium/pull/133) with Polish translation was a bit more descriptive and consistent, but also missed some properties. I wonder if we could work on it a little bit more (@MasterDomino or previous committer would do another shot after this pull request ;]). Something in the middle between this pull request and previous would be great. 

Good work guys. @Gilukm, @MasterDomino

**Comment by MasterDomino** [comment]
@aszwajkowski you're free to copycat my commit and edit it soo it has proper names particle didn't like that i named it my own way but i currently dont have time to work on my pc, soo i allow you to kang my changes ;)

**Comment by Gilukm** [comment]
I pushed a mashup of both our translations. I hope it's what you had in mind ;)

**Comment by ParticleCore** [comment]
Thanks for the help!

**Pull request merged**
